name: "Build"
on:
    pull_request:
        paths-ignore:
            - '.txt'
            - 'LICENSE'
            - 'docs/**'
        branches: [main]
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: CheckOut The Repo
                uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: 17
                    architecture: x64
            - name: Run Synopsys Detect
              uses: synopsys-sig/synopsys-action@v1.8.0
              with:
                  blackduck_url: ${{ secrets.BLACKDUCK_URL }}
                  blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
